hapi:
  fhir:
    implementationguides:
      genomics:
        name: "hl7.fhir.uv.genomics-reporting"
        version: "2.0.0"
        url: "http://hl7.org/fhir/uv/genomics-reporting/package.tgz"
      rwd:
        name: "hl7.fhir.uv.vulcan-rwd"
        version: "1.0.0-ballot"
        url: "http://hl7.org/fhir/uv/vulcan-rwd/2023Jan/package.tgz"
