hapi:
  fhir:
    implementationguides:
      genomics:
        name: "Genomics Reporting"
        version: "2.0.0"
        url: "http://hl7.org/fhir/uv/genomics-reporting/package.tgz"
      rwd:
        name: "Retrieval of Real World Data for Clinical Research"
        version: "1.0.0-ballot"
        url: "http://hl7.org/fhir/uv/vulcan-rwd/2023Jan/package.tgz"
