hapi:
  fhir:
    validation:
      requests_enabled: false
      responses_enabled: false
com:
  essaid:
    fhir:
      hapi:
        extensions:
          provider-class-names:
            - com.essaid.fhir.hapi.extensions.provider.HelloHapi